baseURL = "/"
languageCode = "en-us"
title = "Octavi Font"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

[params]
  avatar = "images/avatar.jpeg"
  author = "Octavi Font"
  seotitle = "Octavi Font - Software Engineer"
  subtitle = "Software Engineering and AI"
  description = "Octavi is a Software Engineer focused on solving infrastructure challenges for Data Science teams."
  email = "octavi@octavifs.com"
  github = "octavifs"
  linkedin = "octavifs"
  #medium = "octavifs"
  customStyle = "styles/custom.scss"

[[menu.main]]
  name = "Blog"
  weight = 10
  identifier = "home"
  url = "/"

# Disabled for now
#[[menu.main]]
#  name = "Tags"
#  weight = 30
#  identifier = "tags"
#  url = "/tags/"
